parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            MJ\Component\User\Model:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Component/User/Model'
                prefix: 'MJ\Component\User\Model'
                alias: User
            MJ\Component\Organization\Model:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Component/Organization/Model'
                prefix: 'MJ\Component\Organization\Model'
                alias: Organization
            MJ\Component\Vehicle\Model:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Component/Vehicle/Model'
                prefix: 'MJ\Component\Vehicle\Model'
                alias: Vehicle
