easy_admin:
    formats:
        date:     'd-m-Y'
        time:     'H:i:s'
        datetime: 'd-m-Y H:i:s'
    list:
        max_results: 17
        actions:
            - { name: 'show', icon: 'search', label: false, title: 'action.show' }
            - { name: 'new', icon: 'plus-circle', css_class: 'btn btn-primary action-new', label: false, title: 'action.new' }
            - { name: 'edit', icon: 'pencil', label: false, title: 'action.edit' }
            - { name: 'delete', icon: 'close', label: false, title: 'action.delete' }
    design:
        brand_color: '#ac2925'
        form_theme: 'vertical'
    entities:
        - MJ\Component\Vehicle\Model\Vehicle
        - MJ\Component\Organization\Model\Organization
